"""ICAP protocol constants per RFC 3507."""

ICAP_VERSION = "ICAP/1.0"

METHOD_OPTIONS = "OPTIONS"
METHOD_REQMOD = "REQMOD"
METHOD_RESPMOD = "RESPMOD"

ENTITY_REQ_HDR = "req-hdr"
ENTITY_RES_HDR = "res-hdr"
ENTITY_REQ_BODY = "req-body"
ENTITY_RES_BODY = "res-body"
ENTITY_NULL_BODY = "null-body"
ENTITY_OPT_BODY = "opt-body"

STATUS_CONTINUE = 100
STATUS_OK = 200
STATUS_NO_CONTENT = 204

DEFAULT_PORT = 1344
DEFAULT_PREVIEW_SIZE = 4096
